services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"